### ISSUE TITLE
Readme needs update regarding OpenCV3

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/himrep#11]
Hi,

the readme (https://github.com/robotology/himrep/blob/master/README_Caffe.md) reports that OpenCV3 is not supported by yarp/icub-main. Thanks to @pattacini this is not the case anymore. Also `himrep` should work nicely now with OpenCV3 as far as I know.

Could you please update the readme @pattacini?

Related to this, the readme also suggests that `CUDA` is an optional dependency. As far as I know, `CUDA` is required for `Caffe`. Thus, maybe we can highlight that `CUDA` really is a hard dependency as soon as you want to compile `caffeCoder`?

Thanks, Tobi

**Comment by pattacini** [comment]
For the first part: ok, done.

For the second part: `CUDA` remains optional since we can run `iol` for example relying on `sparseCoder` (which is btw the very last module I still need to port to `opencv-3.x.y` :disappointed:).

**Comment by Tobias-Fischer** [comment]
Okay, thanks!
