### ISSUE TITLE
MemoryDataLayer moved

### ISSUE THREAD

**Issue by BrutusTT** [robotology/himrep#13]
in the current version of caffe the MemoryDataLayer moved from "caffe/vision_layers.hpp" to "caffe/layers/memory_data_layer.hpp". Not sure how to deal with this since older versions of caffe do not compile nicely on OSX.

**Comment by Tobias-Fischer** [comment]
Hi,
see this: https://github.com/robotology/himrep/pull/10

The reason why this pull request is not merged yet is that we have decreased performance in the newer versions of Caffe. I am not sure whether @GiuliaP found out why.

Closing here.

Best, Tobi
