### ISSUE TITLE
Long delay between launching caffeCoder and recognition

### ISSUE THREAD

**Issue by dcam0050** [robotology/himrep#16]
I have just installed caffe using opencv 2.4.8 together with himrep and when launching the iol2opc pipeline I get the below result which @pattacini has told me implies that recognition is not occuring.

![screenshot from 2016-04-28 16 09 06](https://cloud.githubusercontent.com/assets/4288535/14890723/a20364fa-0d5b-11e6-911e-c705d3fa44c3.png)

After 30-60mins the labels sometimes eventually change to unknown_objectx as they should and recognition with caffe starts to occur much more faster.

This is the log for caffeCoder:

[caffeCoder log.txt](https://github.com/robotology/himrep/files/240816/caffeCoder.log.txt)

**Comment by Tobias-Fischer** [comment]
Do the `?` flicker? Is `SFM` well calibrated (please send a screenshot of the disparity image)? Please also attach the log of `iol2opc` and `himrepClassifier`.

/cc @pattacini

**Comment by pattacini** [comment]
@GiuliaP could you investigate whether the attached log from `caffeCoder` contains some points that look strange to you?

**Comment by dcam0050** [comment]
Yes the ? flickered before. I re-ran the whole pipeline three times again now and it ran perfectly. 

This is the screenshot for the disparity map:

![screenshot from 2016-04-28 16 34 21](https://cloud.githubusercontent.com/assets/4288535/14891542/ff71b904-0d5e-11e6-9cfd-3f8a2e6cff54.png)

That was probably the issue then ... the ? was flickering very often

**Comment by Tobias-Fischer** [comment]
Yes, the `?` has to be there for 5 consecutive seconds without any breaks in between in order to start the training process for a new object.
Can we close this issue then?

**Comment by dcam0050** [comment]
Yep thanks!

**Comment by pattacini** [comment]
@GiuliaP no need to proceed then with my request :smile:

**Comment by GiuliaP** [comment]
The log at a first look seems ok to me... It even seems to be extracting features (I deduce this from the fact that, after opening ports, from line 415 you can see the extraction time:
`W0428 15:55:52.010661 27000 memory_data_layer.cpp:90] MemoryData does not transform array data on Reset()
331.522 msec`

**Comment by GiuliaP** [comment]
Ok good :)

**Comment by pattacini** [comment]
Thanks anyway!
