### ISSUE TITLE
Merge branches

### ISSUE THREAD

**Issue by GiuliaP** [robotology/himrep#23]
Like for the `onthefly-recognition` demo (see [this issue](https://github.com/robotology/onthefly-recognition/issues/3) ) we should merge the `master` and the `nvidia` branches here as well. I can do it, while working on the demo.

**Comment by pattacini** [comment]
@GiuliaP to this end, please branch `devel` off of `master` and use it for this merge.

Afterward, when `devel` is fully tested, we'll proceed to merge it back into `master`.

**Comment by GiuliaP** [comment]
Ok!

**Comment by tanismar** [comment]
I can help with that too in a few days, the robot mode should also work for the tool use demo :)

**Comment by GiuliaP** [comment]
This has been addressed by [97478da](97478da) and I would close the issue @pattacini @tanismar

**Comment by pattacini** [comment]
Yep thanks.
