### ISSUE TITLE
caffeCoder not running on cuda

### ISSUE THREAD

**Issue by tanismar** [robotology/himrep#25]
Hi there, 
I have been using the caffeCoder in the empty/full hand as well as tool recognition pipelines during the last days, without any problem. However today when I tried to execute it (from icub-cuda)  I got the following error: 

Setting .prototxt file to /home/icub/.local/share/yarp/contexts/himrep/imagenet_val_cutfc6.prototxt
Using GPU
Using device_id = 0
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0322 17:55:22.218349 21487 common.cpp:113] Cannot create Cublas handle. Cublas won't be available.
E0322 17:55:22.220235 21487 common.cpp:120] Cannot create Curand generator. Curand won't be available.
F0322 17:55:22.220342 21487 common.cpp:151] Check failed: error == cudaSuccess (38 vs. 0)  no CUDA-capable device is detected
*** Check failure stack trace: ***
Aborted (core dumped)

Any idea what could have happened, did anyone modified the cuda libraries? How can we solve this?

Best, 
Tanis

**Comment by GiuliaP** [comment]
I will look at it today!

**Comment by tanismar** [comment]
Ok, it seems the good old rebooting the machine solved the issue :/
I close it
