### ISSUE TITLE
caffeCoder classifies a subset of the segmented blobs

### ISSUE THREAD

**Issue by gsaponaro** [robotology/himrep#4]
Hi all,

We just tried the IOL application with caffeCoder in Lisbon for the POETICON++ demo scenario, it's pretty cool and gives robust labels, even when stacking objects on top of another (which is relevant for us as we're making a sandwich) :).

We've installed Caffe according to your guide, and customized `iol_caffe.xml.template` to use blobSpotter (instead of lumaChroma + blobExtractor).

Small issue: when we have a stable segmentation of N blobs, sometimes caffeCoder only classifies a subset M<N of them, like in the screenshot below.

![iol_caffe_blobspotter](https://cloud.githubusercontent.com/assets/6716962/8905688/42f14a6a-3460-11e5-8358-af56324535d2.png)

What could be the reason for that and how can we change that behaviour?
Perhaps there is a "minimum area threshold" in one of the modules of the pipeline, similarly to what blobSpotter has?

Thanks.

/cc @vtikha @pattacini @lorejam @AlexAntn

**Comment by pattacini** [comment]
@gsaponaro look at the options `skim_blobs_x_bounds` and `skim_blobs_y_bounds` of the `iolStateMachineHandler` module; they're relevant for the Cartesian positions of blobs. Try to widen them up.

**Comment by lornat75** [comment]
@gsaponaro great to hear this! Please cite this paper in your work if you use this software!

Giulia Pasquale, Carlo Ciliberto, Francesca Odone, Lorenzo Rosasco, Lorenzo Natale, Real-world Object Recognition with Off-the-shelf Deep Conv Nets: How Many Objects can iCub Learn?  [http://arxiv.org/abs/1504.03154]

**Comment by gsaponaro** [comment]
@pattacini, thanks, with the following settings we get the desired blobs now:

```
skim_blobs_x_bounds         (-0.90 -0.10)
skim_blobs_y_bounds         (-0.40  0.40)
```

@lornat75: sure, will do.
