### ISSUE TITLE
linearClassifierModule uses 100% of CPU

### ISSUE THREAD

**Issue by gsaponaro** [robotology/himrep#5]
Hi, I noticed that just launching **linearClassifierModule** (before making connections) makes it use 100% of CPU.

Adding a small delay fixes this. I'm submitting a Pull Request below.

**Comment by gsaponaro** [comment]
Perhaps 0.1s delay is too high a delay if the module must receive stuff at high frequency. Don't know the specifics.

**Comment by pattacini** [comment]
This is a classical example where a blocking read does the job.
@gsaponaro please verify if https://github.com/robotology/himrep/commit/a8d446387183c42d69c8abc62bb677aa503878a0 fixes this issue.

**Comment by gsaponaro** [comment]
Indeed it does! Thanks for the quick reply.
