### ISSUE TITLE
caffeCoder does not compile after recent updates in Caffe's headers organization

### ISSUE THREAD

**Issue by GiuliaP** [robotology/himrep#7]
I just noticed that there have been major updates in Caffe's headers organization with this commit:
https://github.com/BVLC/caffe/commit/300f43f3ae6347ac8e01093f9a57ee99e551ed74

In particular the header `caffe/vision_layers.hpp`, which is included by our file `himrep/modules/caffeCoder/src/CaffeFeatExtractor.hpp` has been removed. Now the file `caffe/layers/memory_data_layer.hpp`should be included in place of the previous one. 

Hence the module now compiles only with versions of Caffe pulled before that commit (23 days ago). However, I didn't update yet the inclusion in `CaffeFeatExtractor.hpp` because it is not backward compatible, and after this change the module would compile only with versions of Caffe pulled after the commit of course.

What is the way to handle this?

**Comment by pattacini** [comment]
Did they somehow **break the API** then? Uhm ... If so, that's bad.
However, perhaps they provide a way to check against the current `Caffe` version in `cmake`. You could then use this information to behave accordingly.

**Comment by GiuliaP** [comment]
I'll try to verify this asking to them. I'll let you know.

**Comment by GiuliaP** [comment]
I have opened an issue on Caffe asking for clarifications: https://github.com/BVLC/caffe/issues/3409.

**Comment by pattacini** [comment]
:+1:

**Comment by pattacini** [comment]
@GiuliaP proposed #10 for addressing this issue, hence we can conveniently close it by now.
